app = "egyptianratscrew"

region = "ord"

kill_signal = "SIGTERM"
kill_timeout = 60

[http_service]
  internal_port = 3000
  force_https = true
  min_machines_running = 0
  auto_stop_machines = "stop"
  auto_start_machines = true

[vm]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256

